inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 130

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'config/application.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/routing/**/*'

RSpec/ExampleLength:
  Max: 10
